server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

spring:
  profiles:
    active:
      - dev

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile:
        - dev      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: gtp1205

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    
---
server:
  port: 8000
spring:
  config:
    activate:
      on-profile:
        - test      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: gtp1205

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
sp:
  jwt:
    secret: product-secret
    token-life-time: 600

